# Generated by Django 5.0.8 on 2024-12-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHaberler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaynak', models.CharField(max_length=100)),
                ('baslik', models.CharField(max_length=255)),
                ('link', models.URLField(unique=True)),
                ('tarih', models.DateTimeField()),
                ('aciklama', models.TextField()),
                ('resim', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
