# Generated by Django 5.0.8 on 2024-12-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHaberler', '0002_haber_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='haber',
            options={'verbose_name_plural': 'Haberler'},
        ),
        migrations.AddField(
            model_name='haber',
            name='goruntulenme_sayisi',
            field=models.IntegerField(default=0),
        ),
    ]
