# Generated by Django 5.0.8 on 2024-12-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHaberler', '0003_alter_category_options_alter_haber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
