# Generated by Django 5.0.8 on 2024-12-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHaberler', '0004_haber_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haber',
            name='goruntulenme_sayisi',
        ),
        migrations.RemoveField(
            model_name='haber',
            name='slug',
        ),
    ]
